# Site Settings
title: Mario Becerra
email: mbecerracontreras@gmail.com
description: >
  Applied Mathematician - Data scientist - Computer scientist
baseurl: ""
url: "https://mariobecerra.github.io"
linkedin_username:  mariobecerracontreras
github_username:  mariobecerra
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
exclude: ['blog_prep']
kramdown:
  input: GFM
